# Buntspecht Multi-Provider Konfiguration Beispiel
# Kopiere diese Datei zu config.toml und passe die Werte an

[mastodon]
# Deine Mastodon-Instanz URL (z.B. "https://mastodon.social")
instance = "https://deine-mastodon-instanz.com"

# Dein Zugangstoken (aus den Mastodon-Einstellungen erhalten)
accessToken = "dein-zugangstoken-hier"

[bot]
# Multi-Provider Konfiguration
# Jeder Provider kann einen eigenen Zeitplan und eigene Konfiguration haben

# Provider 1: Stündliche Ping-Nachrichten
[[bot.providers]]
name = "hourly-ping"
type = "ping"
cronSchedule = "0 * * * *"  # Jede Stunde
enabled = true

[bot.providers.config]
message = "🤖 Stündlicher Ping von Buntspecht!"

# Provider 2: Tägliche Systemstatistiken
[[bot.providers]]
name = "daily-stats"
type = "command"
cronSchedule = "0 9 * * *"  # Jeden Tag um 9:00 Uhr
enabled = true

[bot.providers.config]
command = "uptime"
timeout = 10000

# Provider 3: GitHub Repository-Updates (alle 6 Stunden)
[[bot.providers]]
name = "github-stats"
type = "jsoncommand"
cronSchedule = "0 */6 * * *"  # Alle 6 Stunden
enabled = true

[bot.providers.config]
command = "curl -s 'https://api.github.com/repos/octocat/Hello-World' | jq '{name: .name, stars: .stargazers_count, forks: .forks_count, language: .language}'"
template = "📊 Repository {{name}} ({{language}}): {{stars}} ⭐ und {{forks}} 🍴"
timeout = 15000

# Provider 4: Wöchentliche Zusammenfassung (deaktiviert)
[[bot.providers]]
name = "weekly-summary"
type = "ping"
cronSchedule = "0 10 * * 1"  # Jeden Montag um 10:00 Uhr
enabled = false  # Deaktiviert

[bot.providers.config]
message = "📅 Wöchentliche Zusammenfassung: Eine neue Woche beginnt!"

# Provider 5: Wetter-Updates (alle 3 Stunden)
[[bot.providers]]
name = "weather-updates"
type = "jsoncommand"
cronSchedule = "0 */3 * * *"  # Alle 3 Stunden
enabled = true

[bot.providers.config]
# Beispiel mit OpenWeatherMap API (API-Key erforderlich)
command = "curl -s 'https://api.openweathermap.org/data/2.5/weather?q=Berlin&appid=YOUR_API_KEY&units=metric' | jq '{temp: .main.temp, desc: .weather[0].description, city: .name, humidity: .main.humidity}'"
template = "🌤️ Wetter in {{city}}: {{temp}}°C, {{desc}} (Luftfeuchtigkeit: {{humidity}}%)"
timeout = 10000

[bot.providers.config.env]
API_KEY = "dein-openweathermap-api-schluessel"

[logging]
# Protokoll-Stufe: debug, info, warn, error
level = "info"

# Hinweise:
# - Jeder Provider läuft unabhängig mit seinem eigenen Zeitplan
# - Provider können einzeln aktiviert/deaktiviert werden mit 'enabled = true/false'
# - Verschiedene Provider-Typen können gemischt werden
# - Jeder Provider kann eigene Umgebungsvariablen haben
# - Bei Fehlern in einem Provider werden die anderen nicht beeinträchtigt
#
# Cron-Schedule Beispiele:
# "0 * * * *"       = jede Stunde
# "*/30 * * * *"    = alle 30 Minuten  
# "0 9 * * *"       = jeden Tag um 9:00 Uhr
# "0 9 * * 1"       = jeden Montag um 9:00 Uhr
# "0 */6 * * *"     = alle 6 Stunden
# "0 9,17 * * 1-5"  = Mo-Fr um 9:00 und 17:00 Uhr