# Buntspecht Konfiguration
# Kopiere diese Datei zu config.toml und passe die Werte an

[mastodon]
# Deine Mastodon-Instanz URL (z.B. "https://mastodon.social")
instance = "https://deine-mastodon-instanz.com"

# Dein Zugangstoken (aus den Mastodon-Einstellungen erhalten)
accessToken = "dein-zugangstoken-hier"

[bot]
# Zeitplan fuer das Posten (Standard: "0 * * * *" = jede Stunde)
# Format: "Minute Stunde Tag Monat Wochentag"
# Beispiele:
#   "0 * * * *"     = jede Stunde
#   "*/30 * * * *"  = alle 30 Minuten
#   "0 9 * * *"     = jeden Tag um 9:00 Uhr
#   "0 9 * * 1"     = jeden Montag um 9:00 Uhr
#   "*/15 9-17 * * 1-5" = alle 15 Min zwischen 9-17 Uhr, Mo-Fr
cronSchedule = "0 * * * *"

# Message Provider (Standard: "ping")
# Verfuegbare Provider: ping, command, jsoncommand
messageProvider = "ping"

# Konfiguration fuer den Message Provider
[bot.messageProviderConfig]
# Fuer den ping Provider: die Nachricht die gepostet werden soll
message = "PING"

# Fuer den command Provider: das auszufuehrende Kommando
# command = "date '+Heute ist %A, der %d. %B %Y um %H:%M Uhr UTC'"
# timeout = 30000  # Timeout in Millisekunden (Standard: 30000)
# cwd = "/pfad/zum/arbeitsverzeichnis"  # Arbeitsverzeichnis (optional)
# maxBuffer = 1048576  # Maximale Puffergroesse fuer stdout/stderr (Standard: 1MB)
# [bot.messageProviderConfig.env]  # Umgebungsvariablen (optional)
# MEINE_VAR = "wert"

# Fuer den jsoncommand Provider: Kommando das JSON ausgibt + Template
# command = "curl -s 'https://api.example.com/data' | jq '{name: .name, count: .count}'"
# template = "Statistik: {{name}} hat {{count}} Eintraege"
# timeout = 30000  # Timeout in Millisekunden (Standard: 30000)
# cwd = "/pfad/zum/arbeitsverzeichnis"  # Arbeitsverzeichnis (optional)
# maxBuffer = 1048576  # Maximale Puffergroesse fuer stdout/stderr (Standard: 1MB)
# [bot.messageProviderConfig.env]  # Umgebungsvariablen (optional)
# API_KEY = "dein-schluessel"

[logging]
# Protokoll-Stufe: debug, info, warn, error
level = "info"
