# Buntspecht Konfiguration
# Kopiere diese Datei zu config.toml und passe die Werte an

# Fediverse/Mastodon Accounts
# Du kannst mehrere Accounts konfigurieren und Provider koennen an einen oder mehrere Accounts posten

[[accounts]]
name = "main-account"
instance = "https://mastodon.social"
accessToken = "dein-hauptaccount-token-hier"

[[accounts]]
name = "backup-account"
instance = "https://fosstodon.org"
accessToken = "dein-backup-account-token-hier"

# Optional: Weitere Accounts
# [[accounts]]
# name = "work-account"
# instance = "https://deine-firmen-instanz.com"
# accessToken = "dein-arbeits-token-hier"

[bot]
# Multi-Provider Konfiguration
# Jeder Provider kann einen eigenen Zeitplan und eigene Konfiguration haben
# Jeder Provider kann an einen oder mehrere Accounts posten

# Provider 1: Stuendliche Ping-Nachrichten (an beide Accounts)
[[bot.providers]]
name = "hourly-ping"
type = "ping"
cronSchedule = "0 * * * *"  # Jede Stunde
enabled = true
accounts = ["main-account", "backup-account"]  # Postet an beide Accounts

[bot.providers.config]
message = "🤖 Stuendlicher Ping von Buntspecht!"

# Provider 2: Taegliche Systemstatistiken (nur an Hauptaccount, deaktiviert)
[[bot.providers]]
name = "daily-stats"
type = "command"
cronSchedule = "0 9 * * *"  # Jeden Tag um 9:00 Uhr
enabled = false
accounts = ["main-account"]  # Nur an Hauptaccount

[bot.providers.config]
command = "uptime"
timeout = 10000

# Provider 3: GitHub Repository-Updates (nur an Backup-Account, deaktiviert)
[[bot.providers]]
name = "github-stats"
type = "jsoncommand"
cronSchedule = "0 */6 * * *"  # Alle 6 Stunden
enabled = false
accounts = ["backup-account"]  # Nur an Backup-Account

[bot.providers.config]
command = "curl -s 'https://api.github.com/repos/octocat/Hello-World' | jq '{name: .name, stars: .stargazers_count, forks: .forks_count, language: .language}'"
template = "📊 Repository {{name}} ({{language}}): {{stars}} ⭐ und {{forks}} 🍴"
timeout = 15000

[logging]
# Protokoll-Stufe: debug, info, warn, error
level = "info"

# Hinweise:
# - Jeder Provider laeuft unabhaengig mit seinem eigenen Zeitplan
# - Provider koennen einzeln aktiviert/deaktiviert werden mit 'enabled = true/false'
# - Verschiedene Provider-Typen koennen gemischt werden
# - Jeder Provider kann eigene Umgebungsvariablen haben
# - Bei Fehlern in einem Provider werden die anderen nicht beeintraechtigt
#
# Cron-Schedule Beispiele:
# "0 * * * *"       = jede Stunde
# "*/30 * * * *"    = alle 30 Minuten  
# "0 9 * * *"       = jeden Tag um 9:00 Uhr
# "0 9 * * 1"       = jeden Montag um 9:00 Uhr
# "0 */6 * * *"     = alle 6 Stunden
# "0 9,17 * * 1-5"  = Mo-Fr um 9:00 und 17:00 Uhr
#
# Provider-Typen:
#
# 1. ping Provider:
#    type = "ping"
#    [config]
#    message = "Deine Nachricht hier"
#
# 2. command Provider:
#    type = "command"
#    [config]
#    command = "date '+Heute ist %A, der %d. %B %Y um %H:%M Uhr UTC'"
#    timeout = 30000  # Optional: Timeout in Millisekunden
#    cwd = "/pfad/zum/arbeitsverzeichnis"  # Optional: Arbeitsverzeichnis
#    maxBuffer = 1048576  # Optional: Maximale Puffergroesse
#    [config.env]  # Optional: Umgebungsvariablen
#    MEINE_VAR = "wert"
#
# 3. jsoncommand Provider:
#    type = "jsoncommand"
#    [config]
#    command = "curl -s 'https://api.example.com/data' | jq '{name: .name, count: .count}'"
#    template = "Statistik: {{name}} hat {{count}} Eintraege"
#    timeout = 30000  # Optional: Timeout in Millisekunden
#    cwd = "/pfad/zum/arbeitsverzeichnis"  # Optional: Arbeitsverzeichnis
#    maxBuffer = 1048576  # Optional: Maximale Puffergroesse
#    [config.env]  # Optional: Umgebungsvariablen
#    API_KEY = "dein-schluessel"