# Buntspecht Konfiguration Beispiel - Command Provider
# Kopiere diese Datei zu config.toml und passe die Werte an

[mastodon]
# Deine Mastodon-Instanz URL (z.B. "https://mastodon.social")
instance = "https://deine-mastodon-instanz.com"

# Dein Zugangstoken (aus den Mastodon-Einstellungen erhalten)
accessToken = "dein-zugangstoken-hier"

[bot]
# Zeitplan fuer das Posten (Standard: "0 * * * *" = jede Stunde)
# Format: "Minute Stunde Tag Monat Wochentag"
# Beispiele:
#   "0 * * * *"     = jede Stunde
#   "*/30 * * * *"  = alle 30 Minuten
#   "0 9 * * *"     = jeden Tag um 9:00 Uhr
#   "0 9 * * 1"     = jeden Montag um 9:00 Uhr
#   "*/15 9-17 * * 1-5" = alle 15 Min zwischen 9-17 Uhr, Mo-Fr
cronSchedule = "0 * * * *"

# Message Provider: command
messageProvider = "command"

# Konfiguration fuer den Command Provider
[bot.messageProviderConfig]
# Das auszufuehrende Kommando (erforderlich)
command = "date '+Heute ist %A, der %d. %B %Y um %H:%M Uhr UTC'"

# Optional: Timeout in Millisekunden (Standard: 30000 = 30 Sekunden)
timeout = 10000

# Optional: Arbeitsverzeichnis fuer das Kommando
# cwd = "/pfad/zum/arbeitsverzeichnis"

# Optional: Maximale Puffergroesse fuer stdout/stderr (Standard: 1MB)
# maxBuffer = 1048576

# Optional: Umgebungsvariablen
# [bot.messageProviderConfig.env]
# MEINE_VAR = "ein wert"
# ANDERE_VAR = "anderer wert"

[logging]
# Protokoll-Stufe: debug, info, warn, error
level = "info"