version: '3.8'

services:
  buntspecht:
    # Use pre-built image from GitHub Container Registry
    image: ghcr.io/rmoriz/buntspecht:latest
    # For development, uncomment the line below and comment the image line above
    # build: .
    container_name: buntspecht
    restart: unless-stopped
    volumes:
      # Mount your config file
      - ./config.toml:/app/config.toml:ro
      # Optional: Mount logs directory
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - BUN_ENV=production
      # Optional: Override config path
      # - BUNTSPECHT_CONFIG=/app/config.toml
    # Optional: Health check endpoint
    healthcheck:
      test: ["CMD", "bun", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M