# URL Tracking Middleware Configuration Example
# This middleware adds UTM tracking parameters to all URLs in messages
# By default, URLs are wrapped in HTML anchor tags: <a href="tracked_url">original_url</a>

# Basic configuration
[bot]

[[bot.providers]]
name = "my-provider"
type = "command"
accounts = ["my-account"]
enabled = true

[bot.providers.config]
command = "echo 'Check out our website: https://example.com and our blog: https://blog.example.com'"

# Middleware configuration with URL tracking
[[bot.providers.middleware]]
name = "url-tracker"
type = "url_tracking"
enabled = true

# Basic UTM tracking with defaults
[bot.providers.middleware.config]
# utm_medium defaults to "social" if not specified
# utm_source defaults to "mastodon" if not specified
utm_campaign = "schachnachrichten"
# wrap_in_html defaults to true - URLs will be wrapped in HTML anchor tags

# Advanced configuration example
[[bot.providers]]
name = "advanced-provider"
type = "command"
accounts = ["my-account"]
enabled = true

[bot.providers.config]
command = "echo 'Advanced example with tracking'"

[[bot.providers.middleware]]
name = "advanced-url-tracker"
type = "url_tracking"
enabled = true

[bot.providers.middleware.config]
# Custom UTM parameters
utm_medium = "social"
utm_source = "mastodon"
utm_campaign = "schachnachrichten"
utm_term = "chess_news"
utm_content = "bot_post"

# HTML anchor tag wrapping (default: true)
wrap_in_html = true  # URLs become: <a href="https://example.com/?utm_...">https://example.com</a>

# Custom link text for HTML anchor tags (default: original URL)
link_text = "Visit website"  # URLs become: <a href="https://example.com/?utm_...">Visit website</a>

# Override existing UTM parameters in URLs
override_existing = false

# Skip URLs that already have UTM parameters
skip_existing_utm = false

# Only track specific domains
include_domains = ["example.com", "blog.example.com"]

# Or exclude specific domains (don't use both include and exclude)
# exclude_domains = ["internal.company.com", "localhost"]

# Example with HTML wrapping disabled
[[bot.providers]]
name = "plain-text"
type = "command"
accounts = ["my-account"]
enabled = true

[bot.providers.config]
command = "echo 'Plain text example'"

[[bot.providers.middleware]]
name = "plain-tracker"
type = "url_tracking"
enabled = true

[bot.providers.middleware.config]
utm_medium = "social"
utm_source = "mastodon"
utm_campaign = "schachnachrichten"
# Disable HTML wrapping for platforms that don't support HTML
wrap_in_html = false  # URLs stay as plain text: https://example.com/?utm_...
# link_text is ignored when wrap_in_html is false

# Example with domain filtering
[[bot.providers]]
name = "domain-filtered"
type = "command"
accounts = ["my-account"]
enabled = true

[bot.providers.config]
command = "echo 'Domain filtering example'"

[[bot.providers.middleware]]
name = "selective-tracker"
type = "url_tracking"
enabled = true

[bot.providers.middleware.config]
utm_medium = "social"
utm_source = "mastodon"
utm_campaign = "external_links"

# Only add tracking to external domains, exclude internal ones
exclude_domains = ["internal.company.com", "private.example.com"]

# Example for different social platforms
[[bot.providers]]
name = "bluesky-provider"
type = "command"
accounts = ["bluesky-account"]
enabled = true

[bot.providers.config]
command = "echo 'Bluesky example'"

[[bot.providers.middleware]]
name = "bluesky-tracker"
type = "url_tracking"
enabled = true

[bot.providers.middleware.config]
utm_medium = "social"
utm_source = "bluesky"  # Different source for Bluesky
utm_campaign = "schachnachrichten"
wrap_in_html = true  # Bluesky supports HTML links
link_text = "Check this out"  # Custom text for all links

# Account configuration (required)
[[accounts]]
name = "my-account"
type = "mastodon"
instance = "https://mastodon.social"
accessToken = "your-access-token-here"

[[accounts]]
name = "bluesky-account"
type = "bluesky"
identifier = "your-handle.bsky.social"
password = "your-app-password"

# Multiple middleware example - URL tracking with text transformation
[[bot.providers]]
name = "multi-middleware"
type = "command"
accounts = ["my-account"]
enabled = true

[bot.providers.config]
command = "echo 'Multi-middleware example'"

[[bot.providers.middleware]]
name = "text-transform"
type = "text_transform"
enabled = true

[bot.providers.middleware.config]
transform = "append"
suffix = " #chess #news"

[[bot.providers.middleware]]
name = "url-tracker"
type = "url_tracking"
enabled = true

[bot.providers.middleware.config]
utm_medium = "social"
utm_source = "mastodon"
utm_campaign = "schachnachrichten"
wrap_in_html = true
link_text = "Read more"  # Custom link text for better user experience
# This will run after the text transform, so it will also track any URLs in the appended text