# Buntspecht Configuration - Provider-specific Webhook Secrets
# This example shows how to configure different webhook secrets, hashing methods,
# and headers for each provider

[logging]
level = "info"

# Global webhook configuration (optional fallback)
[webhook]
enabled = true
port = 8080
host = "0.0.0.0"
path = "/webhook"
# Global fallback settings (used if provider doesn't specify its own)
hmacAlgorithm = "sha256"
hmacHeader = "X-Hub-Signature-256"
# Optional global secret as fallback
# secret = "global-fallback-secret"
# hmacSecret = "global-fallback-hmac-secret"

# Account configurations
[[accounts]]
name = "mastodon-main"
type = "mastodon"
instance = "https://mastodon.social"
accessToken = "your-mastodon-token"

[[accounts]]
name = "bluesky-main"
type = "bluesky"
identifier = "your-handle.bsky.social"
password = "your-app-password"

# Provider configurations with individual webhook secrets
[bot]
[[bot.providers]]
name = "github-notifications"
type = "push"
accounts = ["mastodon-main", "bluesky-main"]
visibility = "unlisted"

[bot.providers.config]
# GitHub-style webhook configuration
webhookSecret = "github-webhook-secret-123"
hmacSecret = "github-hmac-secret-456"
hmacAlgorithm = "sha256"
hmacHeader = "X-Hub-Signature-256"

[[bot.providers]]
name = "gitlab-ci"
type = "push"
accounts = ["mastodon-main"]
visibility = "private"

[bot.providers.config]
# GitLab-style webhook configuration
webhookSecret = "gitlab-webhook-secret-789"
hmacSecret = "gitlab-hmac-secret-abc"
hmacAlgorithm = "sha256"
hmacHeader = "X-Gitlab-Token"

[[bot.providers]]
name = "custom-service"
type = "push"
accounts = ["bluesky-main"]
visibility = "public"

[bot.providers.config]
# Custom service with SHA-512 and custom header
webhookSecret = "custom-simple-secret"
hmacSecret = "custom-hmac-secret-def"
hmacAlgorithm = "sha512"
hmacHeader = "X-Custom-Signature"

[[bot.providers]]
name = "legacy-service"
type = "push"
accounts = ["mastodon-main"]

[bot.providers.config]
# Legacy service with only simple secret (no HMAC)
webhookSecret = "legacy-simple-secret-only"
# No HMAC configuration - will use simple secret validation

[[bot.providers]]
name = "no-auth-service"
type = "push"
accounts = ["mastodon-main"]

[bot.providers.config]
# Service with no authentication (not recommended for production)
# No webhook secrets configured - will allow any request